import { randomBytes } from "node:crypto";
import { access, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");

async function exists(path) {
  return access(path, constants.F_OK).then(() => true, () => false);
}

async function createOnce(relativePath, content) {
  const path = resolve(root, relativePath);
  if (await exists(path)) {
    console.log(`Kept existing ${relativePath}`);
    return;
  }
  await writeFile(path, content, { encoding: "utf8", flag: "wx" });
  console.log(`Created ${relativePath}`);
}

const sessionSecret = randomBytes(48).toString("base64url");
const encryptionKey = randomBytes(32).toString("base64url");

await createOnce("apps/gateway/.dev.vars", [
  "# Local-only secrets generated by pnpm setup:local",
  `SESSION_SECRET=${sessionSecret}`,
  `UPSTREAM_ENCRYPTION_KEY=${encryptionKey}`,
  "",
].join("\n"));

await createOnce("apps/web/.env.local", [
  "GATEWAY_ORIGIN=http://127.0.0.1:8787",
  "NEXT_PUBLIC_APP_NAME=Sentinel Edge",
  "DEMO_SENTINEL_API_KEY=",
  "DEMO_UPSTREAM_ID=",
  "DEMO_MODEL=openai/gpt-oss-20b",
  "",
].join("\n"));

console.log("Next: run the local D1 migration, create an administrator, then start the two apps. See docs/QUICKSTART.md.");
